Fix kubectl exec (#61)
Error:
```
$> kubectl exec -ti redis-with-volume-secrets /bin/bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
error: unable to upgrade connection: container not found ("redis")
```